include(FetchContent)
FetchContent_Declare(doctest
    GIT_REPOSITORY https://github.com/doctest/doctest.git
    GIT_TAG v2.5.0)

set(DOCTEST_WITH_MAIN_IN_STATIC_LIB OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(doctest)

add_executable(treelang_tests test_main.cpp test_smoke.cpp)

target_link_libraries(treelang_tests PRIVATE treelang_core doctest)

target_compile_definitions(treelang_tests PRIVATE TREELANG_BUILD_TESTS)

include(${doctest_SOURCE_DIR}/scripts/cmake/doctest.cmake)
doctest_discover_tests(treelang_tests)

add_executable(core_matrix_tests test_main.cpp core/matrix_test.cpp)

target_link_libraries(core_matrix_tests PRIVATE treelang_core doctest)

doctest_discover_tests(core_matrix_tests)

add_executable(core_tests test_main.cpp core/core_test.cpp)

target_link_libraries(core_tests PRIVATE treelang_core doctest)

doctest_discover_tests(core_tests)

add_executable(event_tests test_main.cpp core/event_test.cpp)

target_link_libraries(event_tests PRIVATE treelang_core doctest)

doctest_discover_tests(event_tests)

add_executable(handler_tests test_main.cpp core/handler_test.cpp)

target_link_libraries(handler_tests PRIVATE treelang_core doctest)

doctest_discover_tests(handler_tests)

add_executable(map_tests test_main.cpp map/map_test.cpp)

target_link_libraries(map_tests PRIVATE treelang_core doctest)

doctest_discover_tests(map_tests)

add_executable(entity_tests test_main.cpp entity/entity_event_test.cpp entity/entity_status_test.cpp
                        entity/entity_effect_test.cpp entity/entity_manager_test.cpp)

target_link_libraries(entity_tests PRIVATE treelang_core doctest)

doctest_discover_tests(entity_tests)

add_executable(combat_spell_tests test_main.cpp combat/spell_test.cpp)

target_link_libraries(combat_spell_tests PRIVATE treelang_core doctest)

doctest_discover_tests(combat_spell_tests)
